@startuml
' This is a comment!
entity Entity01 {
  * identifying_attribute : number <<generated>>
  --
  * mandatory_attribute: number 
  optional_attribute1: number <<FK>>
  optional_attribute2: string
}
entity Entity02
entity Entity03
entity Entity04
entity Entity05
entity Entity06
entity Entity07
entity Entity08
Entity01 }|..|| Entity02
Entity03 }o..o| Entity04
Entity05 ||--o{ Entity06
Entity07 |o--|| Entity08
@enduml
