classDiagram
    %% This is a comment!
    class Class01 {
        field1
        field2: string
        method1()
        method2(a: int, b: int): string
    }
    interface Interface01
    Interface01 <|-- Class01
    Class01 --> Class02
    Class01 *-- Class03
    Class01 o-- Class04
    Class01 .. Class05
    note "A free floating note"
    note for Interface01 "A note attached to an interface"
